version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - test_db_data:/var/lib/postgresql/data

  app:
    build: ./
    command: bash -c "go test ./api -cover && go run furniture_store"
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app
    environment:
      - TZ='Europe/Moscow'

volumes:
  postgres_data:
  test_db_data:
